### ISSUE TITLE
依赖安装好后

### ISSUE THREAD

**Issue by coolspeeder** [elva2596/vueBlog#11]
前端构建时出现 依赖不全的情况。。
![image](https://cloud.githubusercontent.com/assets/20675416/26750111/30b32a00-484d-11e7-8bb4-8c940aee61ec.png)
![image](https://cloud.githubusercontent.com/assets/20675416/26750254/5b61f86e-4850-11e7-8c41-3767cfe91ba3.png)

**Comment by elva2596** [comment]
你手动安装一下

**Comment by coolspeeder** [comment]
现在是我从新下载了你的程序，安装后报图 2 的错误，一共三个 errors ，babel-loader 在配置里都写了，怎么会报这个错呢，作者帮我看下吧，我是按照你的 readme 来的
