### ISSUE TITLE
mongoose里面的addCreateAt方法的作用是什么？

### ISSUE THREAD

**Issue by rudyxu1102** [elva2596/vueBlog#5]
找了半天也找不到关于这个方法的介绍，请教一下博主，谢谢

**Comment by elva2596** [comment]
mongolass插件系统。自己定义的。可以看看我贴出来的帖子里面介绍mongolass的文章

**Comment by rudyxu1102** [comment]
@elva2596 不知道帖子在哪里/(ㄒoㄒ)/~~

**Comment by SBB123** [comment]
https://github.com/nswbmw/N-blog/blob/master/book/4.8%20%E7%99%BB%E5%87%BA%E4%B8%8E%E7%99%BB%E5%BD%95.md，这个里边介绍的addCreateAt

**Comment by elva2596** [comment]
参考[我的这个项目](https://github.com/elva2596/my-blog)和[这个](https://cnodejs.org/topic/5856478b491e0754534fb0f4),我的express学习是根据[一起学习Node,js](https://cnodejs.org/topic/581b0c4ebb9452c9052e7acb),第一个链接就是这个项目，里面有大量注释，可以仔细看看
