### ISSUE TITLE
请问在服务器下如何部署？

### ISSUE THREAD

**Issue by Cheese-Yu** [elva2596/vueBlog#8]
buid之后只有dist中只有前端页面，是需要将server文件夹一起放到服务器上吗？然后运行app.js就可以了吗？需要改什么配置吗？从来没有部署过后端应用到服务器，问题有点多。。感谢解答~

**Comment by elva2596** [comment]
后台接口部署搜索Linux部署node
前台部署搜索Nginx部署vue

**Comment by Cheese-Yu** [comment]
谢谢~
